[phases.setup]
nixPkgs = ["nodejs-20"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "npx prisma generate",
  "npx prisma db push --skip-generate --accept-data-loss",
  "npm run build"
]

[phases.start]
cmd = "node .next/standalone/server.js"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
